version: '3'
services:
  tbcontact:
    container_name: tbcontact
    ports:
      - "3004:80"
    build:
      context: ./tbcontact
      dockerfile: Dockerfile
    depends_on:
      - tbcontact-db
    networks:
      - moph-network
  tbcontact-db:
    image: mariadb
    container_name: tbcontact-db
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: Contact_in_tb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 6004:3306
    volumes:
      - tbcontact-dbdata:/var/lib/mysql
      - tbcontact-dblog:/var/log/mysql
      - ./tbcontact/config/my.conf:/etc/mysql/conf.d/config-file.cnf
      - ./tbcontact/init:/docker-entrypoint-initdb.d
    networks:
      - moph-network
  kong-database:
    image: postgres:13
    container_name: kong-database
    networks:
      - kong-net
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpass
    volumes:
      - kong_data:/var/lib/postgresql/data
  kong-migrations:
    image: kong:3.7.0
    command: kong migrations bootstrap
    depends_on:
      - kong-database
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kongpass
  kong:
    image: kong:3.7.0
    container_name: kong
    networks:
      - kong-net
    ports:
      - 8000:8000
      - 8443:8443
      - 127.0.0.1:8001:8001
      - 127.0.0.1:8002:8002
      - 127.0.0.1:8444:8444
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_ADMIN_GUI_URL: http://localhost:8002  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8080:80
    networks:
      - moph-network
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - 8800:8000
      - 9000:9000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
volumes:
  tbcontact-dbdata: {}
  tbcontact-dblog: {}
  portainer_data: {}
  kong_data: {}
networks:
  moph-network:
    driver: bridge
  kong-net:
    external: false